### PR TITLE
modify original PipeRider-Action to support new piperider-cli

### PR DESCRIPTION
**Pull request by wcchang1115**
Signed-off-by: Wei-Chun, Chang <wcchang@infuseai.io>

### CODE REVIEW

**Comment by kentwelcome** [comment]
When we copy the reports to GitHub Action artifact, need also copy the folders `static` and `logo`

**Review by popcornylu — COMMENTED** [review]
I don't think the piperider-action should know dbt existing. It should be more general purpose.

Another problem we should consider is the connector package depedency. How will it work for postgresql or other datasource in the future?

**Comment by kentwelcome** [comment]
> Another problem we should consider is the connector package depedency. How will it work for postgresql or other datasource in the future?


The piperider-action is based on the docker image [`piperider-cli`](https://hub.docker.com/r/infuseai/piperider-cli). We will build this image when releasing piperider-cli. The connector package dependency can be solved at that stage. Andy had already fix it in PR [#84](https://github.com/InfuseAI/piperider-cli/pull/84). Once the new piperider-cli release is ready, we can just remove the pip install part in piperider-action's dockerfile.

**Comment by popcornylu** [comment]
@kentwelcome 
Thanks for your clarification. So we will pack all the connector dependencies in `piperider-cli` image, right? I am afraid that there would be a lot of dependencies in the future. For current solution, it is ok. In the future, i prefer to add options for users to define the depednecy in action params, or from `requirements.txt` in the repo.

**Review by kentwelcome — APPROVED** [review]
LGTM

**Pull request merged**
